# Path: backend/modules/agents/writer_agent.py
# Use: Synthesizes gathered evidence into a comprehensive research report
#      using the same persistent browser tab as the reasoning agent,
#      then saves the output to a file with chunked live-appending.

import os
import logging
import time
from pathlib import Path
from typing import Dict, Any, List

from modules.agents.browser_manager import browser_manager
from modules.ai_orchestrator.platform_config import PLATFORMS

logger = logging.getLogger("MAX.WRITER_AGENT")

DEFAULT_PLATFORM = "gemini"


async def run(input_data: Dict[str, Any], context: Dict[str, Any] = None) -> Dict[str, Any]:
    """
    Final stage of Orchestrator pipeline.
    Reuses the reasoning tab to generate a full research report via chunked prompts.
    """
    goal = input_data.get("goal") or (context or {}).get("goal", "research")
    evaluations: List[dict] = input_data.get("evaluations") or []
    task_id = (context or {}).get("task_id", "default")
    platform_key = input_data.get("platform", DEFAULT_PLATFORM)

    platform_info = PLATFORMS.get(platform_key)
    if not platform_info:
        platform_info = PLATFORMS[DEFAULT_PLATFORM]

    # Reuse the reasoning agent's tab (it already has the full conversation context)
    tab_id = f"reasoning_{task_id}"

    # Prepare output file
    base_dir = Path(os.path.abspath(os.path.dirname(__file__)))
    project_root = base_dir.parent.parent.parent  # backend/modules/agents -> Jarvis
    research_dir = project_root / "Jarvis Generated" / "Research"
    research_dir.mkdir(parents=True, exist_ok=True)

    safe_topic = "".join(c if c.isalnum() or c in "-_ " else "_" for c in goal)[:80].strip().replace(" ", "_")
    file_path = research_dir / f"deep_research_{safe_topic}.txt"

    try:
        # Check if reasoning tab still exists; if not, create fresh
        try:
            await browser_manager.get_tab(tab_id)
            has_context = True
        except Exception:
            logger.info(f"Reasoning tab '{tab_id}' not found. Opening fresh tab.")
            await browser_manager.get_tab(tab_id, url=platform_info.url_new_chat)
            has_context = False

        # ── STAGE 1: Generate outline ──
        logger.info("✍️ Writer Agent: Stage 1 — Generating outline...")

        if has_context:
            # Tab already has the conversation, so the AI knows the topic and evidence
            outline_prompt = (
                f"You have analyzed evidence for the research question: '{goal}'.\n"
                f"Now, generate a detailed 6-8 chapter outline for a comprehensive research report. "
                f"Use ALL the evidence we discussed. Just output the outline, no filler."
            )
        else:
            # Fresh tab — send evidence directly
            evidence_block = _format_evidence(evaluations)
            outline_prompt = (
                f"Topic: '{goal}'.\n"
                f"Evidence:\n{evidence_block}\n\n"
                f"Generate a detailed 6-8 chapter outline for a comprehensive research report."
            )

        # Submit and wait for response using count-aware flow
        pre_count = await browser_manager.inject_and_submit(tab_id, outline_prompt, platform_info)
        outline = await browser_manager.smart_harvester(
            tab_id, platform_info, pre_submit_count=pre_count, timeout=90
        )

        # Start writing the file
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(f"{'='*60}\n")
            f.write(f"DEEP RESEARCH REPORT: {goal.upper()}\n")
            f.write(f"Generated by MAX Orchestrator\n")
            f.write(f"{'='*60}\n\n")
            f.write("--- OUTLINE ---\n")
            f.write(outline + "\n\n")
            f.write("--- MAIN CONTENT ---\n\n")

        logger.info("✍️ Writer Agent: Outline saved. Starting chunked generation...")

        # ── STAGE 2: Chunked content generation ──
        chunks = [
            "Chapters 1 and 2",
            "Chapters 3 and 4",
            "Chapters 5 and 6",
            "Chapters 7 and 8 (if applicable), plus a conclusion",
        ]

        for chunk_label in chunks:
            logger.info(f"✍️ Generating {chunk_label}...")
            write_prompt = (
                f"Based EXACTLY on the outline above, write ONLY {chunk_label} in extreme detail. "
                f"Use professional formatting, deep technical explanations, real-world examples, "
                f"and clear headings. DO NOT write any other chapters right now. "
                f"Start directly with the content."
            )

            # Submit and wait for each chunk properly
            pre_count = await browser_manager.inject_and_submit(tab_id, write_prompt, platform_info)
            chunk_content = await browser_manager.smart_harvester(
                tab_id, platform_info, pre_submit_count=pre_count, timeout=120
            )

            with open(file_path, "a", encoding="utf-8") as f:
                f.write(chunk_content + "\n\n")

            time.sleep(2)  # Small pause between chunks

        # ── STAGE 3: Verification guidance ──
        with open(file_path, "a", encoding="utf-8") as f:
            f.write("\n--- VERIFICATION GUIDANCE ---\n")
            f.write("Claims appearing in only one source should be treated as provisional "
                    "unless corroborated independently.\n")
            f.write(f"\nSources used ({len(evaluations)}):\n")
            for i, ev in enumerate(evaluations, 1):
                url = ev.get("url", "unknown")
                note = ev.get("relevance_note", "")
                f.write(f"  {i}. {url} — {note}\n")

        logger.info(f"✅ Writer Agent: Research report saved to {file_path}")

        # Close the tab — this task's browser session is done
        await browser_manager.close_tab(tab_id)

        return {
            "file_path": str(file_path),
            "message": f"Deep research on '{goal}' is complete. Report saved.",
        }

    except Exception as e:
        logger.error(f"🔴 Writer Agent failed: {e}", exc_info=True)

        # Fallback: write whatever evidence we have directly to the file
        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(f"DEEP RESEARCH REPORT: {goal}\n\n")
                f.write("(Generated via fallback — browser synthesis failed)\n\n")
                for i, ev in enumerate(evaluations, 1):
                    f.write(f"### Source {i}: {ev.get('url', 'unknown')}\n")
                    f.write((ev.get("extracted_facts") or ev.get("relevance_note") or "No details.") + "\n\n")
        except Exception:
            pass

        return {
            "file_path": str(file_path),
            "message": f"Research partially complete (writer error: {e}). Raw evidence saved.",
        }


def _format_evidence(evaluations: List[dict]) -> str:
    """Format evaluation results into a compact text block for the AI."""
    parts = []
    for i, ev in enumerate(evaluations[:12], 1):
        url = ev.get("url", "unknown")
        facts = ev.get("extracted_facts", "")
        note = ev.get("relevance_note", "")
        parts.append(f"[Source {i}] {url}\n{facts}\nRelevance: {note}")
    return "\n---\n".join(parts) if parts else "No evidence available."
